# fly.toml file generated for gopaqueteria on 2022-12-28T13:00:32-07:00

app = "gopaqueteria"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"

  DB_CONNECTION = "mysql"
  DB_HOST = "gcp-us-central1.connect.psdb.cloud"
  DB_PORT = "3306"
  DB_DATABASE = "gopaqueteria"
  DB_USERNAME = "01xbcl8we3w7ya1y1294"
  DB_PASSWORD = "pscale_pw_q2ERBDSi0uq6sQyeLzNbHHGzvlGCo3NSd7d1BmZMkck"
  MYSQL_ATTR_SSL_CA = "/etc/ssl/certs/ca-certificates.crt"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
